name: Build Debian package
description: Build Debian package from source for selected target releases
branding:
  color: red
  icon: package
inputs:
  source_directory:
    description: Directory where Debian sources are, relative to workspace
    required: false
    default: "./"
  artifacts_directory:
    description: Directory where build artifacts will be placed, relative to workspace
    required: false
    default: "./"
  target_architecture:
    description: "Target architecture to build for. Currently supported values: amd64, armhf, arm64"
    required: false
    default: "amd64"
  distribution:
    description: Distribution to build against (e.g. 'stable'). If left blank, it is inferred from the changelog.
    required: false
    default: ""
  dpkg_buildpackage_opts:
    description: Command line parameters provided to 'dpkg-buildpackage' (note that '-a' is automatically provided for target architectures specified by target_architectures)
    required: false
    default: "-us -uc -d --post-clean"
  lintian_opts:
    description: Command line parameters provided to 'lintian'
    required: false
    default: ""

runs:
  using: node12
  main: main.js
