name: Build Debian package
description: Build Debian package from source for selected target releases
branding:
  color: red
  icon: package
inputs:
  source_directory:
    description: Directory where Debian sources are, relative to workspace
    required: false
    default: "./"
  artifacts_directory:
    description: Directory where build artifacts will be placed, relative to workspace
    required: false
    default: "./"
  target_architecture:
    description: "Target architecture to build for. Currently supported values: amd64, armhf, arm64"
    required: false
    default: "amd64"
  docker_image:
    description: Docker image to use for the build (e.g. 'debian:buster-backports'). If left blank, it is inferred from the changelog. Ideally, the base image of this image matches the 'distribution' provided (or inferred from the changelog).
    required: false
    default: ""
  distribution:
    description: Distribution to build against (e.g. 'buster'). If left blank, it is inferred from the changelog. If this is used with 'docker_image', this repository must be available in the image used. Ideally, this would be the base image.
    required: false
    default: ""
  dpkg_buildpackage_opts:
    description: Command line parameters provided to 'dpkg-buildpackage' (note that '-a' is automatically provided for target architectures specified by target_architectures)
    required: false
    default: "-us -uc -d"
  lintian_opts:
    description: Command line parameters provided to 'lintian'
    required: false
    default: ""

runs:
  using: node12
  main: main.js
