name: Build Debian package
description: Build Debian package from source for selected target releases
branding:
  color: red
  icon: package
inputs:
  target_architectures:
    description: Comma-separated options list of target architectures to build for
    required: false
    default: "amd64"
  source_directory:
    description: Directory where Debian sources are, relative to workspace
    required: false
    default: "./"
  artifacts_directory:
    description: Directory where build artifacts will be placed, relative to workspace
    required: false
    default: "./"
  dpkg_buildpackage_opts:
    description: Command line parameters provided to 'dpkg-buildpackage' (note that '-a' is automatically provided for target architectures specified by target_architectures)
    required: false
    default: "-us -uc -d"
  lintian_opts:
    description: Command line parameters provided to 'lintian'
    required: false
    default: ""
  get_dev_packages_from_backports:
    description: Only set to 1 if you know what you are doing. All other values are considered as 0
    required: false
    default: "0"
  _uses_pybuild:
    description: Workaround for https://github.com/pi-top/action-debian-package/issues/3. If set to "1", this will install libpython3.*-minimal for all target architectures, so that pybuild can cross-compile
    required: false
    default: "0"

runs:
  using: node12
  main: main.js
